language: android
sudo: false
install: true
addons:
  sonarcloud:
    organization: "eitan12345om-github"
    token:
      secure: "e97750523d801bb3d958658a3544ddc84487bfb6"

android:
    components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
      - tools
      - platform-tools


    # The BuildTools version used by your project
      - build-tools-28.0.0


    # The SDK version used to compile your project
      - android-26
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-$ANDROID_API_LEVEL

    licences :
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_script :
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./licenses/* "$ANDROID_HOME/licenses"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.android/build-cache
      - $HOME/.m2/repository
      - $HOME/.sonar/cache
      - $HOME/.gradle
      - .gradle

script:
  - ./gradlew build check
  - ./gradlew test
  - ./gradlew sonarqube

before_install:
  - chmod +x gradlew

